// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnO1jUfE1EmzvceZJGr0RmfIcmHCnx2a8',
    appId: '1:919023101679:web:3bbc76aa01e190bca7dd1a',
    messagingSenderId: '919023101679',
    projectId: 'eshop-1006a',
    authDomain: 'eshop-1006a.firebaseapp.com',
    storageBucket: 'eshop-1006a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR-mPtkXdBpb9KKl9cd0ijsKsazrbAWLE',
    appId: '1:919023101679:android:8c930caf28833a2aa7dd1a',
    messagingSenderId: '919023101679',
    projectId: 'eshop-1006a',
    storageBucket: 'eshop-1006a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXh67V6ZzOeOtDy0pRwc5TaCSQl-rrJQ',
    appId: '1:919023101679:ios:f37642053d19e34ba7dd1a',
    messagingSenderId: '919023101679',
    projectId: 'eshop-1006a',
    storageBucket: 'eshop-1006a.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXh67V6ZzOeOtDy0pRwc5TaCSQl-rrJQ',
    appId: '1:919023101679:ios:f37642053d19e34ba7dd1a',
    messagingSenderId: '919023101679',
    projectId: 'eshop-1006a',
    storageBucket: 'eshop-1006a.appspot.com',
    iosBundleId: 'com.example.eshop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnO1jUfE1EmzvceZJGr0RmfIcmHCnx2a8',
    appId: '1:919023101679:web:70a001ec8109a513a7dd1a',
    messagingSenderId: '919023101679',
    projectId: 'eshop-1006a',
    authDomain: 'eshop-1006a.firebaseapp.com',
    storageBucket: 'eshop-1006a.appspot.com',
  );
}
